# -*- coding: utf-8 -*-
"""Hello World.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YVnIYSTR1uhft_Auy62ZgF1Cf-JK762q
"""

print("Hello World!")

"""파이썬 버전확인"""

import sys
print("파이썬 버전은? : ",sys.version)

print("안녕하세요 \r좋은 아침입니다. \r감사합니다.")

print("hello안녕\ngosafdsodbye  1234asdfdsf55 \n raslkdjfldj")

print("hello")
print("")
print("bye")